#!/usr/bin/env node
/* Headless startup smoke test.
 *
 * WHY THIS EXISTS: v1.12.1 shipped with `this.currentVehicle()` — a function
 * that does not exist anywhere in the file — on the first line of
 * discountProfile(). Every engine check passed, because every engine check ran
 * in Node and none of them ever loaded the page. The app was dead on open for
 * every user. A build that verifies the maths and never opens the app is not a
 * verified build.
 *
 * Usage: node test/smoke.js [path-to-index.html]
 */
const { chromium } = require('/tmp/node_modules/playwright');
const path = require('path');

const FILE = path.resolve(process.argv[2] || __dirname + '/../index.html');

/* The v1.11.2 fixture is CAPTURED FROM THE APP, not hand-written. An earlier
   hand-written one passed every scenario against a build that was provably
   broken, because it got the storage key wrong and silently exercised nothing.
   A fixture you invented tests your idea of the app; a fixture you captured
   tests the app. Generated by driving a fresh install (pick a network, pick a
   plan), reading localStorage back, and deleting the keys v1.12 introduced. */
const V1112_STATE = {
  "vehicles": [
    {
      "id": "vuupqlh7",
      "modules": 24,
      "yearFrom": 2022,
      "yearTo": 2026,
      "make": "GMC",
      "model": "Hummer EV Pickup (SUT)",
      "packVariant": "24-module Ultium (Edition 1 / 3X) \u2014 MY2022-2026",
      "usableKWh": 212.7,
      "acMaxKW": 19.2,
      "nativeAC": "J1772",
      "nativeDC": "CCS1",
      "packArchitectureV": 800,
      "lowVoltStationMaxKW": 185,
      "acEfficiency": 0.89,
      "dcEfficiency": 0.952,
      "peakDcKW": 350,
      "curveShape": "800v",
      "curveConfidence": "estimated",
      "curveNote": "TEMPLATE, WITH THREE ANCHORS. Generated from the 800 V platform template at a 350 kW peak \u2014 the same way every other estimated curve in this library is built. It is NOT measured. Three real anchors exist and are consistent with it at the low end: 340+ kW at 13% SOC on a true 350 kW / 1000 V CCS post; ~183 kW at 40% through a NACS adapter on a Tesla V3, which is a 400 V-class station cap and does NOT constrain the native curve; and one full session, 62% to 99% in 51.78 min for 82.6275 kWh dispensed (Meijer 3175 S Rochester Rd, stall KATHLEEN, 12 Aug 2026, charger screen + settled receipt). A previous hand-authored curve sat roughly 30% BELOW this template across 55-95% SOC with no source, and was briefly labelled `observed` and refitted to that single session. Both were wrong; the hand edit has been removed rather than replaced with a new fit. KNOWN RESIDUAL BIAS: even the bare template predicts ~72 min for that 51.78 min session, so it remains ~40% pessimistic above 60% SOC. That is a property of the shared 800 V template, not of this vehicle \u2014 see the SHAPE note at the top of this file. It is recorded as data in observations/, not fitted away.",
      "dcCurve": [
        {
          "soc": 0,
          "kW": 301
        },
        {
          "soc": 5,
          "kW": 336
        },
        {
          "soc": 10,
          "kW": 350
        },
        {
          "soc": 15,
          "kW": 350
        },
        {
          "soc": 20,
          "kW": 336
        },
        {
          "soc": 30,
          "kW": 322
        },
        {
          "soc": 40,
          "kW": 304.5
        },
        {
          "soc": 50,
          "kW": 269.5
        },
        {
          "soc": 55,
          "kW": 231
        },
        {
          "soc": 60,
          "kW": 189
        },
        {
          "soc": 65,
          "kW": 147
        },
        {
          "soc": 70,
          "kW": 119
        },
        {
          "soc": 80,
          "kW": 87.5
        },
        {
          "soc": 90,
          "kW": 59.5
        },
        {
          "soc": 95,
          "kW": 38.5
        },
        {
          "soc": 100,
          "kW": 14
        }
      ],
      "year": 2026,
      "dcCapable": true,
      "libraryId": "gmc-hummer-sut-24",
      "modelYear": 2025,
      "name": "2025 GMC Hummer EV Pickup (SUT)",
      "vin": null,
      "packVerified": true,
      "dcAdapter": {
        "id": "oem-gm-nacs-dc",
        "name": "GM NACS DC Adapter (85836744)",
        "type": "DC",
        "fromConnector": "NACS_DC",
        "toConnector": "CCS1",
        "maxKW": 500,
        "maxVoltage": 1000,
        "maxAmps": 500,
        "brand": "GM",
        "category": "oem",
        "confidence": "verified",
        "oemFor": [
          "GMC",
          "Chevrolet",
          "Cadillac",
          "Buick"
        ],
        "note": "The factory GM unit, rated 500 A at 1000 V (\u221230 \u00b0C to 40 \u00b0C). At that rating the adapter is never your limit \u2014 on a Tesla V3 the 400 V cabinet is what holds you back, not this.",
        "assumed": true
      },
      "acAdapter": null
    }
  ],
  "activeId": "vuupqlh7",
  "stations": [],
  "fx": {
    "USD_CAD": 1.37,
    "asOf": "2026-08-10",
    "source": "user-editable default"
  },
  "usage": {
    "sessionsPerMonth": 4
  },
  "finder": {
    "open": false,
    "q": "",
    "live": [],
    "busy": false,
    "error": null
  },
  "rates": [],
  "place": null,
  "touOverrides": {},
  "nrelKey": null,
  "displayCurrency": null,
  "session": {
    "level": "AC",
    "stationPresetId": "l2-48",
    "station": {
      "id": "l2-48",
      "name": "Level 2 \u2014 48 A / 240 V (11.5 kW)",
      "level": "AC",
      "connector": "J1772",
      "maxKW": 11.5,
      "maxVoltage": 240,
      "maxAmps": 48,
      "note": "Most common home / workplace L2."
    },
    "env": {
      "tempC": 22,
      "enclosed": false,
      "precondition": false,
      "precondEnRoute": false,
      "live": null
    },
    "arrivalSOC": 40,
    "departureSOC": 80,
    "dwellMin": 480,
    "plugInTime": "21:33",
    "locked": {
      "arrival": false,
      "departure": false,
      "dwell": false
    },
    "req": {
      "arrival": null,
      "departure": null,
      "dwell": null
    },
    "solveFor": "departure",
    "granularity": 10,
    "pricing": {
      "networkId": "evgo",
      "planId": "evgo-plusmax",
      "regionId": null,
      "userRate": null,
      "pinned": true
    }
  },
  "trip": {
    "startSOC": 90,
    "startTime": "07:00",
    "reserveSOC": 10,
    "arriveSOC": 30,
    "legs": [
      {
        "type": "drive",
        "label": "Drive out",
        "minutes": 60,
        "consumptionMode": "pct",
        "consumption": 20
      },
      {
        "type": "stop",
        "label": "Dwell & charge",
        "dwellMin": 240,
        "stationPresetId": "l2-48",
        "station": {
          "id": "l2-48",
          "name": "Level 2 \u2014 48 A / 240 V (11.5 kW)",
          "level": "AC",
          "connector": "J1772",
          "maxKW": 11.5,
          "maxVoltage": 240,
          "maxAmps": 48,
          "note": "Most common home / workplace L2."
        },
        "locked": false
      },
      {
        "type": "drive",
        "label": "Drive home",
        "minutes": 60,
        "consumptionMode": "pct",
        "consumption": 20
      }
    ]
  },
  "trips": [],
  "tab": "plan"
};

const SCENARIOS = [
  ['first run — no saved state at all', null],
  ['upgrade from v1.11.2 — session predates `eligibility`', V1112_STATE],
  ['upgrade, no plan selected', (() => {
    const s = JSON.parse(JSON.stringify(V1112_STATE));
    s.session.pricing.planId = null; return s;
  })()],
  ['corrupt — pricing key missing entirely', (() => {
    const s = JSON.parse(JSON.stringify(V1112_STATE));
    delete s.session.pricing; return s;
  })()],
  ['corrupt — session is null', (() => {
    const s = JSON.parse(JSON.stringify(V1112_STATE));
    s.session = null; return s;
  })()],
  ['corrupt — eligibility is a string, not an object', (() => {
    const s = JSON.parse(JSON.stringify(V1112_STATE));
    s.session.eligibility = 'nonsense'; return s;
  })()],
  ['corrupt — memberships is not an array', (() => {
    const s = JSON.parse(JSON.stringify(V1112_STATE));
    s.session.eligibility = { memberships: 'evgo-plusmax' }; return s;
  })()],
  ['network selected, no vehicles at all', (() => {
    const s = JSON.parse(JSON.stringify(V1112_STATE));
    s.vehicles = []; s.activeId = null; return s;
  })()],
  ['hostile — localStorage holds garbage', 'not json at all'],
];

(async () => {
  const browser = await chromium.launch({
    /* The sandbox ships a Chromium; do not let Playwright try to download one. */
    executablePath: process.env.CHROME_BIN || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome',
    args: ['--no-sandbox']
  });
  let failures = 0;

  for (const [label, state] of SCENARIOS) {
    const ctx = await browser.newContext();
    const page = await ctx.newPage();
    const errors = [];
    page.on('pageerror', e => errors.push('UNCAUGHT: ' + e.message));
    page.on('console', m => { if (m.type() === 'error') errors.push('console.error: ' + m.text()); });

    if (state !== null) {
      await page.addInitScript(s => {
        try { localStorage.setItem('evdwell.v1', typeof s === 'string' ? s : JSON.stringify(s)); } catch (e) {}
      }, state);
    }

    await page.goto('file://' + FILE);
    await page.waitForTimeout(700);

    /* Did the app actually paint, or just fail quietly? */
    const alive = await page.evaluate(() => {
      const b = document.body;
      return { text: (b.innerText || '').trim().length,
               hasUI: !!document.querySelector('.card, .stats, #pricing-box, .tabs') };
    });

    const ok = errors.length === 0 && alive.hasUI && alive.text > 50;
    if (!ok) failures++;
    console.log(`${ok ? '  PASS' : '  FAIL'}  ${label}`);
    if (!ok) {
      errors.slice(0, 3).forEach(e => console.log('          ' + e));
      if (!alive.hasUI) console.log('          no UI rendered');
      if (alive.text <= 50) console.log(`          body text only ${alive.text} chars — blank screen`);
    }
    await ctx.close();
  }

  await browser.close();
  if (failures) {
    console.log(`\nsmoke: ${failures} of ${SCENARIOS.length} scenarios FAILED`);
    process.exit(1);
  }
  console.log(`\nsmoke: all ${SCENARIOS.length} scenarios passed — app starts and paints`);
})();
